{# document footer #}
<footer class="footer">
    <div class="content-wrapper">
        <span class="copyright">
            © {{ now.year }}, {{ package.title }}. All rights reserved.
        </span>
        <span class="watermark">
            Built with
            <a href="https://github.com/SassDoc/sassdoc">SassDoc</a>
            and
            <a href="https://github.com/BiosSun/sassdoc-theme-winter">SassDoc Theme Winter</a>.
        </span>
    </div>
</footer>
